### ISSUE TITLE
What is the scm-to-cereal program?

### ISSUE THREAD

**Issue by ming81** [patrikhuber/eos#10]
desc.add_options()
			("help,h",
				"display the help message")
			("model,m", po::value<fs::path>(&scmmodelfile)->required(),
				"a CVSSP .scm Morphable Model file")
			("isomap,t", po::value<fs::path>(&isomapfile),
				"optional isomap containing the texture mapping coordinates")
			("shape-only,s", po::value<bool>(&save_shape_only)->default_value(false)->implicit_value(true),
				"save only the shape-model part of the full 3DMM")
			("output,o", po::value<fs::path>(&outputfile)->required()->default_value("converted_model.bin"),
				"output filename for the Morphable Model in cereal binary format")
			;
(.scm file , isomap file) I am not found!!

**Comment by patrikhuber** [comment]
Hi @ming81,

There is no need to run `scm-to-cereal`. It's just for converting from our internal model format to the public eos cereal format. The model is under `eos/share/sfm_shape_3448.bin` and you can use that directly with the `fit-model` executable.

**Comment by ming81** [comment]
Because I want to change the model, so I want to know how to generate the sfm_shape_3448.bin file!!

**Comment by patrikhuber** [comment]
The eos library is for fitting the model, not for creating one. It does not contain code to _create_ a new 3DMM. This is not a trivial task, you need 3D scans, and dense 3D-3D registration. 
That's why it comes with pre-trained 3DMMs, and it’s also easy to use it with your own (if you already have one or create it elsewhere), by writing your own `load` function that returns an instance of class `MorphableModel`.
Just fyi, our model contains Chinese faces too.

**Comment by ming81** [comment]
scm-to-cereal program is can generate the sfm_shape_3448.bin file? But where is source file? I don't find it in your project?

**Comment by patrikhuber** [comment]
No, as I said it doesn't **create** the .bin file, it **converts** our internal .scm file to the open cereal .bin file. The content is the same: A mean, eigenvalues, basis vectors, as you would expect from a PCA model, and some metadata.

**Comment by ming81** [comment]
thks
