### ISSUE TITLE
extract_texture gives all 0's in python

### ISSUE THREAD

**Issue by ankur2136** [patrikhuber/eos#129]
Generating the mesh works fine.
```console
(mesh, pose, shape_coeffs, blendshape_coeffs) = eos.fitting.fit_shape_and_pose(model, blendshapes, landmarks, landmark_ids, landmark_mapper, image_width, image_height, edge_topology, contour_landmarks, model_contour)
texture = eos.render.extract_texture(mesh, pose, image)
```

texture is a numpy.ndarray of shape 512, 512, 4 with all 0's

I looked at the python bindings. (generate-python-bindings.cpp) which looks correct to me, and I am failing to debug since I installed using pip.
```console
	render_module.def("extract_texture", [](const core::Mesh& mesh, const fitting::RenderingParameters& rendering_params, cv::Mat image, bool compute_view_angle, int isomap_resolution) {
		cv::Mat affine_from_ortho = fitting::get_3x4_affine_camera_matrix(rendering_params, image.cols, image.rows);
		return render::extract_texture(mesh, affine_from_ortho, image, compute_view_angle, render::TextureInterpolation::NearestNeighbour, isomap_resolution);
	}, "Extracts the texture of the face from the given image and stores it as isomap (a rectangular texture map).", py::arg("mesh"), py::arg("rendering_params"), py::arg("image"), py::arg("compute_view_angle") = false, py::arg("isomap_resolution") = 512);
```

**Comment by patrikhuber** [comment]
Hi!

The fact that you're getting a good mesh is encouraging, so I don't think much can be wrong in principle. It might be possible that your image is 1, 3 or 4 channels, whereas the `extract_texture` function expects a specific, different format (3 or 4 channels). Sorry I can't remember from the top of my head. Can you maybe try to run it with the example in `examples/data`? That definitely worked in the past.

Otherwise I'd suggest you install from the repository, and debug. In VS you can attach to a running python.exe and seamlessly debug from the Python to the C++ code - it's really awesome. If you're using Linux, I'm sure there's a similar setup.

You could also just try the C++ code on your image(s) and see whether the same happens.
I'm really sorry I currently unfortunately don't have time to look at this by myself, I'm in my last few weeks of PhD thesis write-up! After that, I would be more than happy to help and fix possible bugs/problems.

**Comment by ankur2136** [comment]
[demo.py.zip](https://github.com/patrikhuber/eos/files/971509/demo.py.zip)

Just added 4 lines to your original code.
```
      import cv2
      image = cv2.imread('../examples/data/image_0010.png')
      texture = eos.render.extract_texture(mesh, pose, image)
      print(texture)
```

I will try the c++ code.

**Comment by patrikhuber** [comment]
Hmm, I believed that worked for me a few weeks ago.

By the way have you actually looked at the full image? It outputs all zeros because the first elements **are** all zeros. Have a look at the other pixel values, like in the middle of the array, they should be non-zero?

**Comment by ankur2136** [comment]
I finally resolved the issue, would create a pull request to improve the demo code. 

Have you considered making dlib as dependency for getting the initial 68 points?

**Comment by patrikhuber** [comment]
Cool!

> Have you considered making dlib as dependency for getting the initial 68 points?

I think it should be up to the library user to use whatever landmark detection he wants. dlib is a huge dependency that I don't want to pull in, not even as an optional dependency. eos is a lightweight library for one purpose: 3D face models and fitting.

Getting 2D landmarks is a somewhat different task and different people use different landmarking algorithms. I actually tried the dlib landmark tracking and wanted to integrate it into the 4dface demo app but it unfortunately didn't work too well for me.

**Comment by patrikhuber** [comment]
> I finally resolved the issue, would create a pull request to improve the demo code.

So, what was the actual issue?

Thanks!

**Comment by ankur2136** [comment]
I removed the hard-coded values in the demo code which were causing the image issue, but even that did not solve the entire problem. (Using dlib to generate the landmarks for other images.)
The actual problem is that the UV map is incorrectly written. 

![9cjgj](https://cloud.githubusercontent.com/assets/6739498/26319550/501b8f86-3ed4-11e7-8305-a0bdef5d8b47.png)

**Comment by patrikhuber** [comment]
Thanks very much for reporting back! Would you mind giving a bit more information regarding this?

I.e. what do you mean by "hard-coded values in the demo code"?

And what do you mean by "the UV map is incorrectly written."? The whole one? Or only a few triangles? I am working quite a lot with the UV map and haven't encountered any issues. Can you describe it in more details?
For example, if I use `write_textured_obj(...)`, and open it in MeshLab, it displays the model fine, including the texture. So what exactly do you mean?

Thanks!

**Comment by patrikhuber** [comment]
I really can't reproduce this - I would be very glad to hear about more details, so that if it's really a problem, I can fix it? :-)

Thanks!

**Comment by ankur2136** [comment]
Here are the generated assets and question regarding UV-map.  
https://stackoverflow.com/questions/43750103/unity-obj-file-rendering-black

**Comment by patrikhuber** [comment]
Thanks for the link! Hmm, but unfortunately it doesn't really help... The comments to your question are definitely wrong, as the mesh **does** come with uv texture coordinates. So no need to generate an uv map for the face, as it's already there.

And the answer by "Mukesh Saini" is not really helpful as it doesn't contain any details except "Bad uv map", which I believe is not true, since we never had any problems with it. And if it is true I'm happy to fix it but need to know **what** is wrong.

Btw, we can send you an alternative set of uv coordinates if you're willing to try? @PhilippKopp do you think we could send @ankur2136 your square uv coords?

**Comment by ankur2136** [comment]
Sure. Email me at anj022@ucsd.edu

**Comment by patrikhuber** [comment]
I think this wasn't an issue with eos, and from our follow-up conversation I think you resolved the issue on your side.
Feel free to reopen if there is a problem in eos.

**Comment by cfoch** [comment]
I have the same problem. This is my code:
https://paste.fedoraproject.org/paste/NS7Cg~NlzoXrsJPkqrQodQ

All the values are 0's. Any idea? I am using the image from the examples which has 3 channels. Besides that, all the values in the isomap are 0. I don't find here what was made to solve this.

**Comment by cfoch** [comment]
All the values are 0.
If I do
```
    x = [i for i in isomap.reshape(-1) if i == 0]
    print(len(x))
    print(isomap.reshape(-1))
```
the amount of items with 0 values are the same of the total items

**Comment by patrikhuber** [comment]
@cfoch I can't reproduce this with `eos` `1.0.1` from pip. When running `demo.py`, and after `extract_texture` I do:

`cv2.imshow("test", isomap)`
`cv2.waitKey()`

it shows a nice extracted texture :-) (The image is transposed, which it shouldn't be - the `eos::core::Image` bindings need to be updated. But it's easy to just transpose the image into the correct orientation.)

It's quite likely the problem is on your end. Try running with a clean eos installation from pip, python-3.7, and run the unmodified `demo.py`, showing the resulting isomap with above two lines.
