### ISSUE TITLE
Analytical derivatives for camera refinement

### ISSUE THREAD

**Issue by inspirit** [patrikhuber/eos#13]
Hello,
can you please provide the derivatives/jacobians for non liner camera refinement.
i was wondering if i can refine the liner camera estimate result but it seems to be no that simple.
thanx in advance!

**Comment by patrikhuber** [comment]
Hi Eugene,

Sorry for the late reply! I'm afraid I don't have the derivatives - but they should be relatively easy to calculate, shouldn't they? What issues did you run into / what's your use-case?
And with "_ refine the liner camera estimate_" do you mean the linear or non-linear?

Cheers,
Patrik

**Comment by inspirit** [comment]
Hi Patrik, sure i meant non linear refinement. i actually modified the pipeline and instead of estimating affine camera i did SE3 camera pose estimate. and then use this pose for landmarks fitting. it requires some changes in fitting algorithm but not much.
now i wonder if there is way to do a non linear refine for the landmarks...

**Comment by patrikhuber** [comment]
Hi Eugene,

Isn't SE3 very similar to the nonlinear estimate we do? SE3 is the same as orthographic projection, right? I.e. estimate scale, 3 rotation angles and 2 translation values?

If we only fit the shape to landmarks, I think that's a rather easy task that can always be solved linearly, why would you want to use a non-linear algorithm there?

Cheers,
Patrik

**Comment by inspirit** [comment]
SE3 is 6-DOF (SO3 - unit quaternion + (X,Y,Z) translation) and it can be non liner refined with LM or GaussNewton by your choice, also with derivatives etc.
what if we have 2d landmarks no in perfect position or jiggling if we get them from video stream for example, so i wanted to do non-liner refine step to reduce the difference in between frames so 3d landmarks do not jiggle or jump too much...

**Comment by patrikhuber** [comment]
Well, the orthographic camera is 6-DOF as well, the _scale_ is basically a Z parameter. So I think the two methods are pretty much the same, or am I missing something? Would you be willing to share your code?

Regarding the landmarks: So you would optimise over multiple frames, with a non-linear algorithm, if I understand correctly. Yep, I think that's a very good idea!

**Comment by inspirit** [comment]
For the SE3 pose i use Ransac with Perspective-Three-Point solver (a direct computation of Absolute Camera position and Orientation) there are lots of implementations around.

**Comment by patrikhuber** [comment]
I've only seen and used P3P/PnP solvers that estimate a camera matrix, which you then have to decompose (e.g. OpenCV `cv::solvePnP)`. I was never able to get correct results with them. I haven't seen one that directly calculates position and orientation - that's why I implemented `estimate_orthographic_camera`, which directly estimates rx, ry, rz, tx, ty and s, and not a matrix.

**Comment by inspirit** [comment]
thats really strange :) it works just perfect for me using normalised (intrinsics applied) image coordinates with 3d shape corresponding points.

**Comment by patrikhuber** [comment]
Hmm :-) Well, maybe. But I think in the end it doesn't matter much, all the algorithms will produce quite similar results.

**Comment by inspirit** [comment]
True, for me it was easier as I know better how to deal with se3 and non linear optimization of se3

**Comment by Thanh-Binh** [comment]
it is very interesting what you wrote. In your algorithm, we can get as results 3 rotation and translation.
If you share your source code, I will test and compare both methods together.

**Comment by inspirit** [comment]
for the se3 camera pose i was using TheiaSfM framework:
https://github.com/sweeneychris/TheiaSfM
it has a ransac based P3P estimator. for the non linear refinement of the pose i'm using Levenberg Marquardt optimization with SE3 derivatives. for the Ransac P3P its quite a lot of code if we look into Theia source code

**Comment by wguo68** [comment]
I also interested in 3d pose for the perspective camera model. I think We can use the estimate camera pose for the affine camera first,then to refine the estimate camera pose for the perspective camera model.

**Comment by patrikhuber** [comment]
I'll finally close this. I've recently implemented a linear algorithm for orthographic 3D pose fitting, so I think the derivatives of the old one are not so important anymore. In any case, if I was to use non-linear camera refinement again, I'd use an angle-axis (or unit quaternion) parameterisation, which would give slightly different derivatives.

Also, with Ceres, one can use AutoDiff (instead of manually deriving the derivatives), which is pretty awesome! There's also an example of this in the `master` branch now (`fit-model-ceres`), for perspective and orthographic camera estimation.

Thanks again for this nice discussion @inspirit! :-)
