### ISSUE TITLE
Shape fit system solve

### ISSUE THREAD

**Issue by inspirit** [patrikhuber/eos#16]
I was wondering why do estimate solution using inverse here:
https://github.com/patrikhuber/eos/blob/master/include/eos/fitting/linear_shape_fitting.hpp#L122
the system is positive definite matrix so it should be possible to solve it using LDLT/LLT without any inverse. its like 4-5x faster compared to inverse with SVD you are doing now.

**Comment by patrikhuber** [comment]
I think you're right. I'm not sure what happens if we don't use a high-enough regularisation though - the system might not have a solution then, and SVD might provide a better approximate (pseudo-inverse). At the time I implemented it, I didn't think so much about it and just using `::inv` with `DECOMP_SVD` seemed easiest and safest. I'm not sure speed is really an issue - when I last measured, I think it took less than 5ms.

But anyway, thank you very much for bringing this up. It's an excellent suggestion. I don't currently have time to test and verify it (implementing it is quick, but I want to make sure it really works - if you want to do it, I'll happily accept a well-tested PR - sadly there's no unit-tests, but a function like that would be a bit hard to unit-test anyway, or at least I wouldn't really know how). Using `solve()` would certainly be more appropriate, and the free speed gain very welcome too.

**Comment by Thanh-Binh** [comment]
If you give the source code of your implementing LDLT/LLT instead of the original, I am very happy for testing it.

**Comment by patrikhuber** [comment]
I can sketch it here, I don't think I'll have time to compile it this week:

Current:

```
	Mat AtOmegaARegInv = AtOmegaAReg.inv(cv::DECOMP_SVD);
	Mat AtOmegatb = A.t() * Omega.t() * b;
	Mat c_s = -AtOmegaARegInv * AtOmegatb;
```

New (not tested), but I think it should be roughly like this:

```
Mat c_s;
bool non_singular = cv::solve(AtOmegaAReg, A.t() * Omega.t() * b, c_s, cv::DECOMP_CHOLESKY);
```

In the current equation there is a minus, I'd have to look up where that comes from, it might be needed in my code-sketch too.

See also documentation of [cv::solve](http://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html#bool solve(InputArray src1, InputArray src2, OutputArray dst, int flags)).

**Comment by inspirit** [comment]
Well I'm doing it with Eigen lib. And both LDLT and LLT solvers work just fine. On good desktop PC u will probably hardly notice the diff however SVD is several times slower. 
In your impl you also allocate huuuge camera matrix to projects PCAs and mean shape -- this matrix makes around half megabyte! Which is totally waste of time and space. You can simply iterate over basis and points and project them separately filling the solve system in the same loop

**Comment by patrikhuber** [comment]
@inspirit: That's true, space-wise. Though an `Eigen::SparseMatrix` might solve that. Computation-wise I'm not so sure - one matrix multiplication of two big matrices might be faster than a manual for-loop. Eigen probably parallelises that, possible also the auto-vectoriser kicks in. The only right answer here is profiling the code. And of course it will depend on the architecture as well.

**Comment by Thanh-Binh** [comment]
I have just quickly tested the new version and compared with the old one.
In my test, the new one speeds up about 2x and run stablly.
Thanks

**Comment by patrikhuber** [comment]
I came across this today in a related context and looked at the math, a minus is not neccessary, so my code-sketch above is correct. The minus is there because I used `.inv()`, so we "manually" have to solve for `c_s`, while `cv::solve` directly gives `c_s`.

**Comment by inspirit** [comment]
thats strange, in my experiments i use minus, otherwise the coefficients move the shape into opposite direction. ```VecXd c_s = -ldlt.solve(AtOmegatb);```

**Comment by patrikhuber** [comment]
Hmm. I'll have to have a closer look then. Maybe @Thanh-Binh can comment in the meantime, he seemed to have well-tested my pseudo-code above without the minus.

Maybe there's a difference in the solvers on what they output? But that would be rather odd?

**Comment by Thanh-Binh** [comment]
I do not about ldlt, so that I use cv::solve(), and it works oerfectly as mentioned last month.

**Comment by patrikhuber** [comment]
I had a look at the original paper today and I tested it in the code as well. The minus definitely needs to be there, otherwise, the shapes are wrong. It can be put either in front of the "b" or in front of what comes out of the solver.

So the above should be:

```
bool non_singular = cv::solve(AtOmegaAReg, -A.t() * Omega.t() * b, c_s, cv::DECOMP_CHOLESKY);
```

Thank you very much @inspirit for your comments!

**Comment by patrikhuber** [comment]
http://math.stackexchange.com/questions/473432/positive-definite-and-transpose

**Comment by patrikhuber** [comment]
@inspirit: I'm really curious why you say AtA is positive definite. As I see it, AtA is only positive definite if A has full rank, and I don't think this is guaranteed here. (see e.g. http://math.stackexchange.com/questions/473432/positive-definite-and-transpose). We don't even have the guarantee that A has more rows than columns, if we only use 15 or so landmarks, and estimate 60 shape coefficients, that's definitely not the case. And even if num_rows > num_cols, that's no guarantee for A having full rank?

Or are you just assuming it is positive definite because so far it has worked for you in practice? (afaik Eigen's LDLT has no check if the system was actually solvable).

I'm really curious and would be very thankful for a reply! :-)

**Comment by inspirit** [comment]
well if you are going for general solution that should work with 16 landmarks cross 60 coefficients then of course you should do it with SVD. in my case i'm absolutely sure that i have 68 landmarks and 33 coefficients in my system. you also enforce system stability by increasing diagonal values with regularization parameter. all together it pretty much guaranties the system can be solved with simple LDLT and even with LLT. but then as i mentioned above this is the case for good/known input

**Comment by patrikhuber** [comment]
Ok, thank you for your clarification. I see. I completely agree! Thanks :-)

**Comment by patrikhuber** [comment]
5047d78ff6d083952e7a8966af4c9db3ecca2510 and 0cc4b9a97bed0c06cfc8c625165d8f895694c985 now completely switch solving the shape fitting to Eigen. That's another factor 10-50x speed-up compared to the last improvements, and solving the system now takes <0.1 to 1ms, depending on number of landmarks and coefficients.

I'm leaving this ticket open for a bit, I want to change the Blendshape fitting to Eigen as well and possibly have a look at inspirit's idea regarding camera matrix (though I don't think the latter one will give much speed-up).

**Comment by patrikhuber** [comment]
I'll close this for now, the Blendshape fitting is now in Eigen as well, and all changes have been released in [v0.12.1](https://github.com/patrikhuber/eos/releases/tag/v0.12.1).

Regarding the camera matrix `P`, I'll leave it for now. We are currently working on multi-frame fitting and we will see if it will be an issue there (because `P` will be significantly bigger there). If it'll be an issue, we'll change it.

Thanks again for everybody's contributions.

**Comment by Thanh-Binh** [comment]
Congratulation Patrik for speed-up your sw! Is it a common performance problem with opencv, so that we can even speed-up the supervise descent model? What do yo think?

**Comment by patrikhuber** [comment]
@Thanh-Binh Thanks! Yes I measured quite a few times before and OpenCV was always quite slow for linear algebra operations, even for medium or small sized matrices. I haven't measured OpenCV 3.1 though, maybe it's gotten better. Any way Eigen is the safer bet in my opinion.

You raise a good point, if the matrix multiplication is a bottleneck in superviseddescent (I'm not sure it is), then switching to Eigen would definitely be a benefit. Let's discuss that in the respective repository.

**Comment by Thanh-Binh** [comment]
@patrikhuber I am not sure that openCV3.1 better.
