### ISSUE TITLE
Precalibrated projective camera

### ISSUE THREAD

**Issue by Andyjk1406** [patrikhuber/eos#168]
Firstly, a great library - thanks!

Is there any update on using a pre-calibrated projection camera (OpenCV calibration) ?
My aim is to recover the pose - like solvePnP in OpenCV ideally (although I am aware that there may be some issues with OpenGL coordinate system orientation).

So given that I know the camera parameters (fx, fy, cx, cy) and have also (radially) undistorted the images before feeding them into the pipeline, I would think this is an easier problem to solve, than when the camera is uncalibrated?

Has anyone managed to achieve this? I am not quite sure how/where to insert my intrinsic camera parameters. Do I need to use Ceres? Any help appreciated!

Thanks

**Comment by Ostnie** [comment]
@Andyjk1406 Hello, I would like to ask whether this project can achieve data enhancement? That is, I enter the 3D face data, he can change a variety of expressions such as angry sadness? I see in the function seems to be able to achieve but did not find an example or use the method.
I am very sorry for asking a question that is not related to your question here, but I really do not know who to ask, thank you very much

**Comment by patrikhuber** [comment]
@Ostnie I removed your comment as it is unrelated to this question.

@Andyjk1406 Hey, Thanks!

solvePnP solves for a perspective camera I think - perspective projection does not work out-of-the-box with the eos fitting because the perspective projection is nonlinear.
I think undistorting the image and then fitting might be an interesting idea. I think once you know the camera parameters, even if it's a (nonlinear) perspective camera, you might be able to do linear shape fitting. Maybe something like [Hu et al.](https://www.researchgate.net/publication/313904336_Efficient_3D_Morphable_Face_Model_Fitting)?
Another idea, as you mention, is to use Ceres - you could have a look at the `fit-model-ceres` example.

**Comment by patrikhuber** [comment]
(Possibly related: #64, #104)

**Comment by patrikhuber** [comment]
I'm going to close this, as there isn't really an issue with the `eos` library. Both the approach with Ceres as well as the approach by Hu et al. work quite well, just require a bit of implementation.

Feel free to re-open if any issue remains.
