### ISSUE TITLE
BFM fitting problem

### ISSUE THREAD

**Issue by ForestWang** [patrikhuber/eos#172]
Hi Patrik:

I'm tring to use BFM2009 model on eos.
i'm working on eos version 0.12.2. 

1. first using convert_bfm2009_to_raw_binary.m covert 01_MorphableModel to bfw.raw which is about 246M
2. using bfm-binary-to-cereal.cpp convert bfw.raw  to bfm.bin which is about 247M.

3. then using 
landmarkMappings ;
{
	 9   48188; chin bottom
	18   38886; right eyebrow outer-corner (18)
	19   39636; right eyebrow between middle and outer corner
	20   40030; right eyebrow middle, vertical middle (20)
	21   40238; right eyebrow between middle and inner corner
	22   40433; right eyebrow inner-corner (19)
	23   41172; left eyebrow inner-corner (23)
	24   41368; left eyebrow between inner corner and middle
	25   41578; left eyebrow middle (24)
	26   42011; left eyebrow between middle and outer corner
	27   42646; left eyebrow outer-corner (22)
	28   8291 ; bridge of the nose (parallel to upper eye lids)
	29   8305 ; middle of the nose, a bit below the lower eye lids
	30   8314 ; above nose-tip (1cm or so)
	31   8320 ; nose-tip (3)
	32   6783 ; right nostril, below nose, nose-lip junction
	33   7687 ; nose-lip junction
	34   8331 ; nose-lip junction (28)
	35   8977 ; nose-lip junction
	36   9879 ; left nostril, below nose, nose-lip junction
	37   1832 ; right eye outer-corner (1)
	38   3760 ; right eye pupil top right (from subject's perspective)
	39   5050 ; right eye pupil top left
	40   6087 ; right eye inner-corner (5)
	41   4546 ; right eye pupil bottom left
	42   3516 ; right eye pupil bottom right
	43   10731; left eye inner-corner (8)
	44   11758; left eye pupil top right
	45   12919; left eye pupil top left
	46   14859; left eye outer-corner (2)
	47   13191; left eye pupil bottom left
	48   12157; left eye pupil bottom right
	49   5523 ; right mouth corner (12)
	50   6155 ; upper lip right top outer
	51   7442 ; upper lip middle top right
	52   8345 ; upper lip middle top (14)
	53   9506 ; upper lip middle top left
	54   10799; upper lip left top outer
	55   11199; left mouth corner (13)
	56   10179; lower lip left bottom outer
	57   9277 ; lower lip middle bottom left
	58   8374 ; lower lip middle bottom (17)
	59   7471 ; lower lip middle bottom right
	60   6566 ; lower lip right bottom outer
	61   5909   ; 61 not defined - would be right inner corner of the mouth
	62   7322 ; upper lip right bottom outer
	63   8354 ; upper lip middle bottom
	64   9386 ; upper lip left bottom outer
	65   10941  ; 65 not defined - would be left inner corner of the mouth
	66   9141 ; lower lip left top outer
	67   8367 ; lower lip middle top
	68   7194 ; lower lip right top outer
}
as fitting landmarkmaps.
4. using fit-model-simple.cpp for the test.
but the result is strange,
![result](https://user-images.githubusercontent.com/5412083/34760070-3b33b0c4-f619-11e7-9a26-7c19851a41db.png)

Red point is my 68 ibug points, green points is projected 68 points from bfm vertices.
is there anything wrong with my processing?

thank you very much!

after

**Comment by patrikhuber** [comment]
Hi ForestWang,

The older versions of eos had a number of bugs with the BFM, for example, the old converter script converted the basis vectors with a wrong scaling. These have all been fixed over the last couple of months. You have to use a version that is newer than 23 Nov 2017 (for example, the current master head). If you really want to stay at your old version of eos, you might be able to use these new converter scripts (https://github.com/patrikhuber/eos/tree/master/share/scripts) with the older version of eos, but I'm really not sure about whether I fixed anything in the library code too to make the BFM work properly - but if you go through the commit history of fixes relating to the BFM (around November 2017), you should see.

From your screenshot, it's also possible some of your mappings are wrong, you should check them (and make sure e.g. indices are not off-by-one). You Can also try the new mappings in the share/ directory.

I'm going to close this issue as they occur on an old eos version, which should be all fixed in the versions after 23 Nov 2017. But feel free to report back how it goes.

**Comment by ForestWang** [comment]
Thank you for your kindness, Patrik. I'll use latest master version script to convert BFM model. and compare with 0.12.2'result. any result will update here.

**Comment by ForestWang** [comment]
The generated model with 0.12's scripts and 0.13's scripts are the same.

**Comment by patrikhuber** [comment]
As I said, it has to be the latest master version or at least newer than 23 Nov. v0.13.0 is older (22 Oct).
You can use v0.14.0 which I released yesterday.
