### ISSUE TITLE
Build on Xcode 9.3 fails: It seems to define __cplusplus to 201703L without having <optional>

### ISSUE THREAD

**Issue by Yang8510** [patrikhuber/eos#201]
When I built with Xcode, it came out the error "optional" not found. When I change it to experimental/optional, the error turns to boost/shared_ptr.hpp auto_ptrs.

**Comment by juan-cardelino** [comment]
I'm having a similar issue, but after solving the optional part, had problems with variant. It seems that for Xcode 9.3, the following ward fails: 
``#if (__cplusplus >= 201703L || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L))
-------------------------
After forcing to disable that (using && 0) it gives me the following error:
Showing All Errors Only
/Users/juan/juanc/soft/develop/eos/include/eos/morphablemodel/MorphableModel.hpp:151:60: Call to unavailable member function 'value': 
-------------------------
I'm using Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0

**Comment by patrikhuber** [comment]
Thank you for the report and details @juan-cardelino.
It seems that in Xcode 9.3 (Apple clang-902.0.39.1), Apple may have set `__cplusplus ` to `201703L`, without providing `<optional>`. This is quite a bummer, and potentially a mistake on their part.

I've added Xcode 9.3 to travis (9266d8e3ea16457780e69d4f18d3c883a5ee677c) so that we can track it, and indeed it fails there as well.

It's weird that after "manually" editing that check with `&& 0` you get that `Call to unavailable member function 'value'` error. Maybe you haven't changed it in all places? Have you changed it in [include/eos/cpp17/optional_serialization.hpp](https://github.com/patrikhuber/eos/blob/master/include/eos/cpp17/optional_serialization.hpp) too?
You should definitely be able to make it work by making it use the `eos::cpp17` drop-in replacements, like it works for C++14 compilers.

I am afraid I won't have time to properly look at that in the next few weeks, but above should really get you going.

**Comment by juan-cardelino** [comment]
Dear Patrik,
      Thanks for your quick answer. I agree that it is a mistake of XCode. About the replacement, I didn't check it thoroughly, because I had a linux box and switched to it, in which BTW worked like a charm. I'll give it another try and let you know.
Thanks again.
Best,
       Juan

**Comment by juan-cardelino** [comment]
I've carefully searched all occurrences and disabled all of them. Then I got an error on auto_ptr, like @Yang8510. But I realized it was actually a boost error. I replaced my current boost (1.60) by the newest one (1.67) and worked like a charm.
Just for adding a little detail, I'm building on OSX High Sierra (10.13.4).
Thanks for the help.
Best,
        Juan

**Comment by patrikhuber** [comment]
@juan-cardelino Hey cool, that's awesome! Thank you very much for reporting back.
Hehe yes I thought the boost error was something like that. And eos just uses boost for the example apps, the eos library does not require boost.

I'm glad all is working well now :-)

So I guess we just need to add something to that `ifdef` that for example checks for AppleClang or something like that.

**Comment by juan-cardelino** [comment]
Thank you very much for the help. Great work!

**Comment by patrikhuber** [comment]
@akrymski What's your error? I am sure you can fix it by adjusting above `#define`. Xcode updated their compiler recently so it depends what version you're on, you just need to find out whether it has usable optional/variant or not and set above define accordingly, and it should work.

**Comment by patrikhuber** [comment]
This problem probably doesn't exist anymore in newer compiler versions, and eos compiles fine on macos-13 and macos-14, see the latest CI runs. So I'll close this.
