### ISSUE TITLE
Implementation for ios

### ISSUE THREAD

**Issue by DmitryBorin** [patrikhuber/eos#202]
Hello! 
My name is Dmitry, I am a student and interested in face approximations in the video on low-resources devices.

Great works! 
You wrote that successfully launched eos on ios. Could you tell me what changes are needed for this? Or maybe you still have the code? 

Thank you!

**Comment by xkampotx** [comment]
There are no problems in using eos for iOS.
Readme says `just add the following directories to your include path` which is Header Search Paths in Xcode (Project build settings) and link opencv2.framework (and related to it frameworks) to your project.
Also, I did face the issue with Eigen imports. Fixed by changing `#include <Eigen/Core>` to just `#include <Core>`
