### ISSUE TITLE
why the extracted isomap is so blurring

### ISSUE THREAD

**Issue by yyssmm** [patrikhuber/eos#212]
Thank you for sharing your code. But I have a question about that why the extracted isomap is so blurring.

**Comment by patrikhuber** [comment]
Hi,
I'm afraid your report is not very specific. Do you have an example? With the original image? I suspect your input image is low-res, that's why the extracted isomap looks blurry.
You can also try to use other interpolation schemes, like setting `TextureInterpolation` to `TextureInterpolation::Area` for example.
You can also use something like OpenGL for texture extraction, if you're serious about it.

I'm going to close this in the meantime as this issue is not useful without more information.

**Comment by yyssmm** [comment]
Hi,
Thank you for your hearing from you. My original image is 2000*2992, the extracted isomap looks blurry.  I send the original image and the extracted isomap to you through the attachment.Thank you!
![out isomap](https://user-images.githubusercontent.com/28679695/43381887-a27afd9a-9408-11e8-971c-98ea2e140459.png)

**Comment by yyssmm** [comment]
Hi,
Thank you for your hearing from you. My original image is 2000*2992, the extracted isomap looks blurry.  I send the original image and the extracted isomap to you through the attachment.Thank you!
![out isomap](https://user-images.githubusercontent.com/28679695/43381887-a27afd9a-9408-11e8-971c-98ea2e140459.png)


 
![y](https://user-images.githubusercontent.com/28679695/43382087-4b3eb430-9409-11e8-866a-989c1b3109e3.jpg)

**Comment by yyssmm** [comment]
It works for me. Thank you very much!!

**Comment by yyssmm** [comment]
It works for me. Thank you very much!! May I ask you another question? Do you know if given a 3D model, how to extract its isomap?
