### ISSUE TITLE
What is a pts file and how could one produce it?

### ISSUE THREAD

**Issue by davidmoseler** [patrikhuber/eos#217]
The fit-model-simple requires a "pts" file, but there is no documentation on how should one go to produce one. Although the python interface solved this problem for me (as it does not need such a file), it is still a problem for those who go through the trouble of compiling eos from source and then find out that, beyond a face image in a .png file, they also need a "pts", which is far from being a widespread format.

**Comment by patrikhuber** [comment]
You're right, this might be worth documenting. Actually me or eos have nothing to do with that format, it is being used by the ibug group (http://ibug.doc.ic.ac.uk/resources/facial-point-annotations/), which most people doing computer vision and faces are familiar with. But of course we shouldn't assume that for a repository like eos, whose audience is potentially much larger.

I don't think this is necessarily a problem though, because no-one says that you should use `.pts` files and you certainly don't have to. If you look at the `fit-model` (or `fit-model-simple`) example code, you'll see that what the eos fitting expects is an `eos::core::LandmarkCollection<Eigen::Vector2f>`, and this is simple and well documented - it's a list of 2D landmark points, with each of them having an identifier associated with them (so they can be mapped to corresponding 3D model points). So it is completely up to you how you fill the  `eos::core::LandmarkCollection<Eigen::Vector2f>` with values, it's trivial to write your own function that reads a different landmarks format into it.

Do you have a suggestion what exactly we should mention and where we could maybe add that information?

There's also a few related questions, if you search for "pts" in the closed issues you'll find some more info like e.g. #69, #31 or my guide answering [this question](https://github.com/patrikhuber/eos/issues/15#issuecomment-161558994).

**Comment by patrikhuber** [comment]
> they being binary, it is almost impossible to make an inference about the format. I found decoders (reading from pts), but not the opposite. ibug only provided .pts files for specific datasets, not tools to create a .pts file from a general face picture.

The .pts files are text files, you can open them with any text editor. Try Notepad++... (but Windows Notepad works too).
True, they don't specifically define the format, but let's be honest, it's pretty trivial to figure out and adjust it to your liking.

> In my view, the command line tool should probably have the option to accept a simpler human-readable format closer to that of Eigen::Vector2f, in such a way that you could take any picture and use something like OpenCV to find and export the landmarks (as pairs of coordinates). The way it is, you need to find the landmarks AND convert them to .pts, only so that the command line tool can decode it. This sounds like an unnecessary complication to the process.

The same as above really. I think you just haven't found out how to open the pts files. Just open them in a text editor. They're human-readable and as simple as it can get - they're just a list of coordinates. You can trivially write them by hand or with any other library/program.

**Comment by davidmoseler** [comment]
This would make a lot of sense, except that I downloaded the SCUT-FB550, and, when I go to the folder "facial landmark" and open any of the thousands of ".pts" files with vim, I only get rubish. I searched a lot for an example of a pts file with the intent of looking the format (I also did not find the "data" folder for eos repo nor succeeded in compiling eos), but the only ones I found where in non-readable formats.

Summarizing, a big portion of my day was trying to find an example of an actual pts file, but without success. Can you point to some example of a pts file?

**Comment by patrikhuber** [comment]
There is one right in eos, you can even view the contents directly on GitHub: https://github.com/patrikhuber/eos/blob/master/examples/data/image_0010.pts

You can also download any of the ibug datasets from the link I posted earlier (https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/) - scroll down a bit to "Download:", and then for example download LFPW, and open any of the .pts files with a text editor.

I have no idea what "SCUT-FB550" is, I've also never heard it in the context of ibug (though I certainly don't know all of their datasets). Google also didn't turn up any useful hints. I think whatever it is, it must by coincidence have .pts files too that are totally different and have nothing to do with the commonly used ones we're talking about here.

**Comment by davidmoseler** [comment]
Thanks! Knowing that the pts format is human-readable, all I needed was an example of it. That did it.

Maybe for future reference, it would be interesting to link this example in the README.

**Comment by patrikhuber** [comment]
This exact example is linked in the [Sample code](https://github.com/patrikhuber/eos#sample-code) section of the Readme, and it specifically mentions "_ibug landmarks_". I believe that this is more than enough, together with the [easy to find example files](https://github.com/patrikhuber/eos/tree/master/examples/data) (and this folder even has a readme linking to the ibug page!). Anyone remotely serious about faces and computer vision has seen such landmark files before and knows what to do with them, or if not, will be able to google "ibug landmarks" and the ibug website turns up as the first hit.
Furthermore there is various clear documentation [right at the top of the app](https://github.com/patrikhuber/eos/blob/9405338e29b7023d3495ed2cbbfb08904b2c6946/examples/fit-model.cpp#L57-L63), `fit-model --help` outputs for `-l` "2D landmarks for the image, in ibug .pts format", and if someone is really still lost, they can [look at the read_pts_landmarks](https://github.com/patrikhuber/eos/blob/9405338e29b7023d3495ed2cbbfb08904b2c6946/include/eos/core/read_pts_landmarks.hpp#L37-L89) function.

**Comment by tiancaipipi110** [comment]
@patrikhuber still not sure how to reproduce these points tho. Shall one use photoshop, manually mark the points, then save the points layer as .png and somehow convert it into .pts, or shall one use some software to define the locations of the 68 points in order?

**Comment by gigadeplex** [comment]
@tiancaipipi110 so these points are just XY coordinates on an image. When you want to get these you can either do one of two things:

1. Look at the image and manually write down each pixel position you want to use. (This is a very tedious process and really just unscalable lol). If you want to do this however, you should look into annotation tools like imglab from dlib.

2. Just use a shape predictor (that is trained on whatever features you want to extract), and let computer do this for you.

I'm hoping you picked number 2 because that's the most time efficient solution. To demonstrate how to do this, I've made a demo here: https://github.com/gigadeplex/dlib-eos.
This example uses a shape predictor that was trained on 68 keypoints on the human face.
