### ISSUE TITLE
Unable to compile on OSX

### ISSUE THREAD

**Issue by MaG21** [patrikhuber/eos#222]
I'm unable to compile on OSX due to #201. After upgrading boost and manually changing several preprocessor directives:

[ 12%] Building CXX object examples/CMakeFiles/fit-model-simple.dir/fit-model-simple.cpp.o
In file included from /Users/mag/files/Sources/CPP/eos/examples/fit-model-simple.cpp:28:
In file included from /Users/mag/files/Sources/CPP/eos/include/eos/morphablemodel/MorphableModel.hpp:38:
In file included from /Users/mag/files/Sources/CPP/eos/include/eos/cpp17/variant_serialization.hpp:26:
/Users/mag/files/Sources/CPP/eos/3rdparty/cereal/include/cereal/types/variant.hpp:34:10: fatal error: 'variant' file not found
#include <variant>
         ^~~~~~~~~
1 error generated.

**Comment by patrikhuber** [comment]
As mentioned in #201, you just need to fiddle a bit with the `#define` [here](https://github.com/patrikhuber/eos/blob/9405338e29b7023d3495ed2cbbfb08904b2c6946/include/eos/cpp17/variant.hpp#L25) (and also the same in the file `variant_serialization.hpp`), and find out what `#define` is needed, and whether Xcode actually works with `<variant>`, or otherwise use the `#else` branch there.
I'm closing this as a duplicate.
