### ISSUE TITLE
About iterations on pose estimation and shape fitting steps

### ISSUE THREAD

**Issue by anny0316** [patrikhuber/eos#242]
Hello Huber:
   In your paper, you've mentioned iterations. But, in the programs, I have no find where is iteration, I have read the "fit-model-simple.cpp" and other relevant codes. What's wrong? Please help me, Sorry to bother with this. Thanks!

**Comment by anny0316** [comment]
I am sorry , another question.  In program "fit-model" using BFM2009, but I can't find the edge-topology file.

**Comment by patrikhuber** [comment]
Hi,

I am only going to answer briefly since these are help questions and not issues with the eos library.

1. Iterations: The iterations are done inside the `fit_shape_and_pose` function.
2. I think you are confusing texture remapping (texturing, uv-mapping, etc.) and per-vertex colour/albedo/texture PCA model.
3. Just debug into it and see what's going on. "modify some assert" sounds potentially a bit dodgy if you had to do that. The eos wiki has a bit more information about [using the BFM](https://github.com/patrikhuber/eos/wiki#using-the-library-with-the-basel-face-model-bfm).
4. The BFM2009 doesn't contain expressions I think, and the BFM2017 contains a PCA expression model. You can find that all in the literature and on their website.

I would recommend that you just play around with things more to learn about them, read the literature in more details, and maybe find an appropriate place to ask remaining questions (like colleagues/supervisor etc.). The GitHub issues are for developer **issues** and discussions about the eos library, and not for "help" questions.

**Comment by anny0316** [comment]
Thanks a lot!

**Comment by Chen-Jinlong** [comment]
> 1. Program "fit-model-simple.cpp" fit a picture using BFM2009, but the result shows the BFM's mean face, I only hide the function "extract_texture" and modify some assert. What's wrong with it?
> 2. I want to run the "fit-model.cpp" fit a picture using BFM2009, how to modify the blendshape option? Its default value is "expression_blendshapes_3448.bin"?

Could please tell me how to modify assert ?Which one ?
