### ISSUE TITLE
how to get the expression_blendshapes.bin file for BFM model

### ISSUE THREAD

**Issue by LeonLIU08** [patrikhuber/eos#282]
I'd like to change the model from sfm3448 model to BFM model. I have generated the bfm2009.bin file and download the bfm2009_edge_topology.json file from the wiki tag of this repo. However, I find the blend shapes file (expression_blendshapes_3448.bin) is not suitable for the BFM model. 

So I'd like to ask where to get the corresponding .bin file for BFM model. Thanks very much.

**Comment by patrikhuber** [comment]
Hi,

I think it was asked/discussed a few times in the issues here how to get expressions for either BFM.
Could you have a look & search through the issues (open & closed) here please?
Feel free to post back with any remaining questions, best in the appropriate issue, if one of the existing one fits, otherwise here.

Thank you.

**Comment by ascust** [comment]
@patrikhuber Hi, I want to ask the same question. I have looked through all the related questions, and could not find the answer. How are we going to get this "expression_blendshapes.bin" for the BFM model?

**Comment by sunjunlishi** [comment]
much better expression

**Comment by patrikhuber** [comment]
Relevant discussion here which should give all the info needed: https://github.com/patrikhuber/eos/issues/147. Please read through the whole thread.

Since this is a recurring theme, you could also open a thread in the [Discussions](https://github.com/patrikhuber/eos/discussions) section, perhaps the people in the community working on BFM/FaceWarehouse expressions could gather the information there and help each other.
