### ISSUE TITLE
Helen test error

### ISSUE THREAD

**Issue by zhaishengfu** [patrikhuber/eos#290]
good projects! I tested using helen image as follows
![3084329562_1](https://user-images.githubusercontent.com/7630101/70693348-3d0dc080-1cf8-11ea-87a8-1e965a4cf2a6.jpg)
and I see your paper this image has good result
![image](https://user-images.githubusercontent.com/7630101/70693373-4dbe3680-1cf8-11ea-8639-dbf251fcd63b.png)
but when running with this framework, it gets the following result:
![image](https://user-images.githubusercontent.com/7630101/70693414-629aca00-1cf8-11ea-9f85-c0f4890ff584.png)

 why do you think this is not tem same as yours? I used the 3448 sfm bin model and the image is from helen and i got the 2d informaiton from helen mat information "pt2d"

**Comment by zhaishengfu** [comment]
Is seems that your model has fewer vertices, do you use the 845 vertices model? If so, I think your result is better and can you provide the 845 vertices model bin?

**Comment by patrikhuber** [comment]
Thanks!

Your fitting result looks pretty much identical to the one in the paper/wiki. Everything looks good. There might be small differences because of different numbers of iterations or different regularisation values.

The result may seem different to you because I upscaled the images before drawing the mesh. You can easily do that by upscaling the image and then calling `draw_wireframe(...)` with the upscaled image.

I used the 3448 vertices model for these results. The eos readme describes how to obtain the 845 model - it tells you to go to the Uni Surrey website www.cvssp.org/facemodel for more info.
