### ISSUE TITLE
how to set the initial value of Orthographic Parameter?

### ISSUE THREAD

**Issue by cupwater** [patrikhuber/eos#58]
Hi! I found that in "include/fitting/nonlinear_camera_estimation.hpp":
 line 262:    parameters[5] = 110.0;
and   line 262: 
... cost_function_with_derivative(cost_function, 0.0001);
how you set the initial value of orthographic parameters ? Because  when I use eos code to do my reconstruction work, I found that the initial values in your code didn't work.

**Comment by patrikhuber** [comment]
For `parameters[5]`, which is the frustum-scale, it's set so that our face model is projected to the screen space with a size of about half the window or something like that. It's really just a very rough estimate. It always converges for me, even if for example the "true" value is double or more or something like that. I suspect that maybe the model you're using is much smaller or much bigger (like an order of magnitude or more), so you'd probably need to adjust that value. You can just have a look at the value of a point and where it gets projected to; step through the code, or you can even do that by hand, it's just a few matrix multiplication. You'll then see if the point ends up being at location [10000, 10000] or something like that, and can find a reasonable default for the frustum-scale.

**Comment by cupwater** [comment]
Thanks, I set a smaller value to parameters[5], and now it works. As you said, my model is bigger. But I still cannot  figure out why I works.

**Comment by patrikhuber** [comment]
It's using the standard OpenGL orthographic projection model (in fact, using `glm::ortho` and `glm::project`). Stepping through the code and maybe get a good book/tutorial should certainly help if you're interested in that topic. Also [this function](https://github.com/patrikhuber/eos/blob/master/include/eos/fitting/detail/nonlinear_camera_estimation_detail.hpp#L41) might help you understand.

**Comment by cupwater** [comment]
thanks!
