### ISSUE TITLE
About blendshape fitting

### ISSUE THREAD

**Issue by LCLL** [patrikhuber/eos#71]
@patrikhuber 
I want to know if the coefficients achieved from the function "fit_blendshapes_to_landmarks_linear" are in range [0..1] ? 
Thanks.

**Comment by patrikhuber** [comment]
We're using standard linear least squares in this function, so no, the coefficients are not constrained. Internally I'm actually using a NNLS solver (non-negative LS) for this function (which is the correct way to go since the blendshapes are linear (positive) offsets). It's not my solver, but I might be able to share it in the future. However, in practice, in a few tests I've done, the results looked pretty similar.

Do you have any issue with it, or why the question?

**Comment by LCLL** [comment]
Thank you for your quick reply.
I just use Facial Action Coding System to construct the blendshapes so that the coefficients need to be set in range [0...1]. I use projection-based gradient descent to get the coefficients and want to find is there any more efficient way to solve it. Do you have any idea about it ?

**Comment by patrikhuber** [comment]
As I mentioned (and I think this applies to your case too), NNLS is what you want.

Can you share your FACS blendshapes? How did you construct them and from what data?

**Comment by LCLL** [comment]
Yes, I just found that the Ceres provides NNLS solvers (http://ceres-solver.org/nnls_tutorial.html) that is what I need. I will try to compare it with the projection based gradient descent methods.
Thank you.

**Comment by patrikhuber** [comment]
> Yes, I just found that the Ceres provides NNLS solvers (http://ceres-solver.org/nnls_tutorial.html) that is what I need.

This is actually not NNLS. NNLS is non-negative least squares. What you linked to is non-linear least squares. Big difference. I don't know though why the Ceres html filename is "nnls_tutorial.html", there's nothing about "nnls" there :-)

**Comment by patrikhuber** [comment]
You can use the function [`fit_blendshapes_to_landmarks_nnls(...)`](https://github.com/patrikhuber/eos/blob/devel/include/eos/fitting/blendshape_fitting.hpp#L138) now. Make sure to run `git submodule update --init` after pulling, to get the required submodule.
